CREATE TABLE pedidos(
    id SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    DATA DATE DEFAULT CURRENT_DATE,
    EMPRESA VARCHAR(50),
    ITEM VARCHAR(100),
    UNIDADE VARCHAR(2),
    QUANTIDADE INT
)
